apiVersion: v1
kind: Service
metadata:
  name: phpfpm
  namespace: demo
spec:
  selector:
    app: phpfpm
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
