kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: demo
  labels:
    app: nginx
spec:
  volumes:
    - name: nginx-config-volume
      configMap:
        name: nginx-config
  containers:
    - image: nginx:1.21.1-alpine
      name: nginx
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
